# Docker Compose for local testing of SweetHome3D Add-on
# Use this to test the addon locally before deploying to Home Assistant

version: '3.8'

services:
  sweethome3d:
    build:
      context: ./sweethome3d
      dockerfile: Dockerfile
      args:
        BUILD_FROM: alpine:3.20
    ports:
      - "8099:8099"
    volumes:
      - ./test-data:/var/www/html/data
      - ./test-config:/data/options.json:ro
    environment:
      - OPTIONS_JSON=/data/options.json
    restart: unless-stopped

# To test locally:
# 1. Ensure test-data directory exists
# 2. Run: docker-compose up --build
# 3. Access http://localhost:8099
# 4. Test saving/loading home designs
