build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20"
  armhf: "ghcr.io/home-assistant/armhf-base:3.20"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20"
  i386: "ghcr.io/home-assistant/i386-base:3.20"
labels:
  org.opencontainers.image.title: "SweetHome3D"
  org.opencontainers.image.description: "SweetHome3D JS - Interior design application for Home Assistant"
  org.opencontainers.image.source: "https://github.com/HVitureira/ha-sweethome3d"
  org.opencontainers.image.licenses: "GPL-2.0"
args:
  TEMPIO_VERSION: "2024.01.0"