name: HASweetHome3D
version: "1.1.1"
slug: hasweethome3d
description: SweetHome3D JS - Interior design application for Home Assistant
url: https://github.com/HVitureira/ha-sweethome3d
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
init: false
options:
  php_max_execution_time: 300
  php_memory_limit: "256M"
  php_upload_max_filesize: "200M"
  php_post_max_size: "200M"
  homeassistant_address: ""
  homeassistant_token: ""
  use_ssl: true
schema:
  php_max_execution_time: int(30,3600)?
  php_memory_limit: str?
  php_upload_max_filesize: str?
  php_post_max_size: str?
  homeassistant_address: str?
  homeassistant_token: password?
  use_ssl: bool?
panel_icon: mdi:home-floor-3
panel_title: HASweetHome3D
panel_admin: false
ingress: true
ingress_port: 8099
ingress_stream: false
hassio_api: true
hassio_role: default
homeassistant_api: true
auth_api: false
full_access: false
apparmor: false
map:
  - share:rw
  - config:rw