name: Build Add-on

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Get information
      id: info
      uses: home-assistant/actions/helpers/info@master
      with:
        path: "./sweethome3d"

    - name: Check if add-on should be built
      id: check
      run: |
        if [[ "${{ steps.info.outputs.architectures }}" =~ ${{ matrix.arch }} ]]; then
          echo "build_arch=true" >> $GITHUB_OUTPUT
        else
          echo "build_arch=false" >> $GITHUB_OUTPUT
        fi

    - name: Login to GitHub Container Registry
      if: env.BUILD_ARCH == 'true'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build ${{ matrix.arch }} add-on
      if: steps.check.outputs.build_arch == 'true'
      uses: home-assistant/builder@2024.03.5
      with:
        args: |
          --${{ matrix.arch }} \
          --target /data/sweethome3d \
          --generic ${{ steps.info.outputs.version }}
